movie_library/routes.py
import uuid
import datetime
import functools
from flask import (
    Blueprint,
    render_template,
    session,
    redirect,
    request,
    current_app,
    url_for,
    flash,
)
from dataclasses import asdict
from movie_library.forms import MovieForm, ExtendedMovieForm, RegisterForm, LoginForm, ResetPasswordForm, RequestResetForm, UpdateAccountForm
from movie_library.models import Movie, User
from passlib.hash import pbkdf2_sha256
from flask_mail import Message
from movie_library import mail
from pymongo.errors import DuplicateKeyError


pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)

def login_required(route):
    """
    A decorator to ensure a user is logged in before accessing a route.

    If the user is not logged in, they are redirected to the login page.

    Args:
        route (function): The route to protect.

    Returns:
        function: The decorated route.
    """

    @functools.wraps(route)
    def route_wrapper(*args, **kwargs):
        if session.get("email") is None:
            return redirect(url_for(".login"))

        return route(*args, **kwargs)

    return route_wrapper


@pages.route("/")
@login_required
def index():
    """
    Renders the user's movie watchlist.

    Returns:
        str: The rendered HTML of the index page.
    """
    user_data = current_app.db.user.find_one({"email": session["email"]})
    user = User(**user_data)

    movie_data = current_app.db.movie.find({"_id": {"$in": user.movies}})
    movies = [Movie(**data) for data in movie_data]
    return render_template(
        "index.html",
        title="Movies Watchlist",
        movies_data=movies,
    )


@pages.route("/register", methods=["GET", "POST"])
def register():
    """
    Renders the registration page and handles user registration.

    If the user is already logged in, they are redirected to the index page.

    Returns:
        str: The rendered HTML of the registration page.
    """
    if session.get("email"):
        return redirect(url_for(".index"))

    form = RegisterForm()

    if form.validate_on_submit():
        user = User(
            _id=uuid.uuid4().hex,
            email=form.email.data,
            password=pbkdf2_sha256.hash(form.password.data),
        )

        if current_app.db.user.find_one({"email": form.email.data}):
            flash("An account with this email already exists.", category="danger")
            return redirect(url_for(".register"))

        try:
            current_app.db.user.insert_one(asdict(user))
        except DuplicateKeyError:
            flash("An account with this email already exists.", category="danger")
            return redirect(url_for(".register"))

        flash("User registered successfully!", "success")

        return redirect(url_for(".login"))

    return render_template(
        "register.html", title="Movies Watchlist - Register", form=form
    )

@pages.route("/login", methods=["GET", "POST"])
def login():
    """
    Renders the login page and handles user login.

    If the user is already logged in, they are redirected to the index page.

    Returns:
        str: The rendered HTML of the login page.
    """
    if session.get("email"):
        return redirect(url_for(".index"))

    form = LoginForm()

    if form.validate_on_submit():
        user_data = current_app.db.user.find_one({"email": form.email.data})
        if not user_data:
            flash("Login failed. Please check your email and password.", category="danger")
            return redirect(url_for(".login"))
        
        user = User(**user_data)

        if user and pbkdf2_sha256.verify(form.password.data, user.password):
            session["user_id"] = user._id
            session["email"] = user.email

            return redirect(url_for(".index"))
        
        flash("Login failed. Please check your email and password.", category="danger")

    return render_template("login.html", title="Movies Watchlist - Login", form=form)
            

@pages.route("/account", methods=["GET", "POST"])
@login_required
def account():
    """
    Renders the account page and handles updating user account information.
    """
    form = UpdateAccountForm()

    if form.validate_on_submit():
        user_data = current_app.db.user.find_one({"email": session["email"]})
        user = User(**user_data)

        # Verify current password
        if user and pbkdf2_sha256.verify(form.password.data, user.password):
            # Update email
            current_app.db.user.update_one(
                {"_id": user._id},
                {"$set": {"email": form.email.data}}
            )
            # Update session email
            session["email"] = form.email.data

            flash("Your account has been updated!", "success")
            return redirect(url_for(".account"))
        else:
            flash("Incorrect password. Please try again.", "danger")
    elif request.method == "GET":
        # Pre-fill the form with current user data
        form.email.data = session["email"]

    return render_template("account.html", title="Account", form=form)

@pages.route("/logout")
def logout():
    """
    Logs the user out and redirects to the login page.

    Returns:
        werkzeug.utils.redirect: A redirect to the login page.
    """
    current_theme = session.get("theme")
    session.clear()
    session["theme"] = current_theme

    return redirect(url_for(".login"))


def send_reset_email(user):
    """
    Sends a password reset email to the user.

    Args:
        user (User): The user to send the email to.
    """
    token = user.get_reset_token()
    msg = Message(
        "Password Reset Request",
        recipients=[user.email],
    )
    msg.body = f"""To reset your password, visit the following link:
{url_for('pages.reset_token', token=token, _external=True)}

If you did not make this request then simply ignore this email and no changes will be made.
"""
    mail.send(msg)


@pages.route("/reset_request", methods=["GET", "POST"])
def reset_request():
    """
    Renders the page to request a password reset and handles the form submission.
    """
    if session.get("email"):
        return redirect(url_for(".index"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user_data = current_app.db.user.find_one({"email": form.email.data})
        if user_data:
            user = User(**user_data)
            send_reset_email(user)
        flash("An email has been sent with instructions to reset your password.", "info")
        return redirect(url_for(".login"))
    
    return render_template("reset_request.html", title="Reset Password", form=form)

@pages.route("/reset_request/<token>", methods=["GET", "POST"])
def reset_token(token):
    """
    Renders the page to reset a user's password and handles the form submission.
    """
    if session.get("email"):
        return redirect(url_for(".index"))
    user = User.verify_reset_token(token)
    if user is None:
        flash("That is an invalid or expired token", "warning")
        return redirect(url_for(".reset_request"))
    
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = pbkdf2_sha256.hash(form.password.data)
        current_app.db.user.update_one(
            {"_id": user._id}, 
            {"$set": {"password": hashed_password}}
        )
        flash("Your password has been updated! You can now log in.", "success")
        return redirect(url_for(".login"))
    return render_template("reset_token.html", title="Reset Password", form=form)



@pages.route("/add", methods=["GET", "POST"])
@login_required
def add_movie():
    """
    Renders the add movie page and handles adding a new movie.

    Returns:
        str: The rendered HTML of the add movie page.
    """
    form = MovieForm()

    if form.validate_on_submit():
        movie = Movie(
            _id=uuid.uuid4().hex,
            title=form.title.data,
            director=form.director.data,
            year=form.year.data,
        )

        current_app.db.movie.insert_one(asdict(movie))
        current_app.db.user.update_one(
            {"_id": session["user_id"]}, {"$push": {"movies": movie._id}}
        )


        return redirect(url_for(".movie_added", _id=movie._id))

    return render_template(
        "new_movie.html",
        title="Movies Watchlist - Add Movie",
        form=form,
    )


@pages.route("/added/<string:_id>")
def movie_added(_id: str):
    """
    Renders a confirmation page after a movie has been added.

    Args:
        _id (str): The ID of the movie that was added.

    Returns:
        str: The rendered HTML of the movie added page.
    """
    movie = Movie(**current_app.db.movie.find_one({"_id": _id}))
    return render_template("movie_added.html", movie=movie)


@pages.route("/edit/<string:_id>", methods=["GET", "POST"])
@login_required
def edit_movie(_id: str):
    """
    Renders the edit movie page and handles editing a movie.

    Args:
        _id (str): The ID of the movie to edit.

    Returns:
        str: The rendered HTML of the edit movie page.
    """
    movie = Movie(**current_app.db.movie.find_one({"_id": _id}))
    form = ExtendedMovieForm(obj=movie)
    if form.validate_on_submit():
        movie.title = form.title.data
        movie.director = form.director.data
        movie.year = form.year.data
        movie.cast = form.cast.data
        movie.series = form.series.data
        movie.tags = form.tags.data
        movie.description = form.description.data
        movie.video_link = form.video_link.data
        movie.image_link = form.image_link.data

        current_app.db.movie.update_one({"_id": movie._id}, {"$set": asdict(movie)})

        return redirect(url_for(".movie", _id=movie._id))
    return render_template("movie_form.html", movie=movie, form=form)


@pages.get("/movie/<string:_id>")
def movie(_id: str):
    """
    Renders the movie details page.

    Args:

movie_library/templates/macros/fields.html
{% macro render_text_field(field) %}
<div class="form__group">
    {{ field.label(class="form__label") }}
    {{ field(class="form__field") }}
    
    {% for error in field.errors %}
        <span class="form__error">{{ error }}</span>
    {% endfor %}
</div>
{% endmacro %}

{% macro render_area_field(field) %}
<div class="form__group">
    {{ field.label(class="form__label") }}
    {{ field(row=4, class="form__field", style="resize: none;") }}
    
    {% for error in field.errors %}
        <span class="form__error">{{ error }}</span>
    {% endfor %}
</div>
{% endmacro %}

movie_library/templates/macros/footer.html
{% macro footer(current_year) %}
<footer class="footer">
    <small>Copyright &copy; {{ current_year }} Movie Watchlist. All rights reserved.</small>
</footer>
{% endmacro %}

movie_library/templates/macros/nav.html
{% from "macros/svgs.html" import moon, sun %} {% macro header(email, theme) %}
<header class="header">
  <div class="nav-container">
    <a href="{{ url_for('pages.index') }}" class="header__logo">
      <svg class="logo__icon">
        <use
          href="{{ url_for('static', filename='img/icons.svg') }}#movie-watchlist-logo"
        ></use>
      </svg>
      <span class="logo__name">Watchlist</span>
    </a>
    <nav class="nav">
      {% if not email %}
      <a
        href="{{ url_for('pages.login') }}"
        class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.login') }}"
      >
        <span class="nav__item">Log in</span>
      </a>
      <a
        href="{{ url_for('pages.register') }}"
        class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.register') }}"
      >
        <span class="nav__item">Sign up</span>
      </a>
      {% else %}
      <a
        href="{{ url_for('pages.index') }}"
        class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.index') }}"
      >
        <span class="nav__item">Movies</span>
      </a>
      <a
        href="{{ url_for('pages.account') }}"
        class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.account') }}"
      >
        <span class="nav__item">Account</span>
      </a>
      <a href="{{ url_for('pages.logout') }}" class="nav__link">
        <span class="nav__item">Log out</span>
      </a>
      {% endif %}
      <a
        href="{{ url_for('pages.toggle_theme', current_page=request.path) }}"
        class="nav__link nav__item--icon"
      >
        <span class="nav__item">
          {% if theme == "dark" %}
          <svg class="nav__icon">
            <use
              href="{{ url_for('static', filename='img/icons.svg') }}#icon-sun-colorful"
            ></use>
          </svg>
          {% else %}
          <svg class="nav__icon">
            <use
              href="{{ url_for('static', filename='img/icons.svg') }}#icon-moon-colorful"
            ></use>
          </svg>
          {% endif %}
        </span>
      </a>
    </nav>
  </div>
</header>
{% endmacro %}

movie_library/templates/macros/svgs.html
{% macro sun(class_) %}
    <svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" viewBox="0 0 24 24">
  <defs>
    <radialGradient id="sunRadial" cx="50%" cy="50%" r="50%" fx="50%" fy="50%">
      <stop offset="0%" style="stop-color:#FFEB3B;stop-opacity:1" />
      <stop offset="100%" style="stop-color:#FFC107;stop-opacity:1" />
    </radialGradient>
    <filter id="sunGlow" x="-50%" y="-50%" width="200%" height="200%">
      <feDropShadow dx="0" dy="0" stdDeviation="1.5" flood-color="rgba(255, 255, 255, 0.7)" flood-opacity="1"/>
    </filter>
  </defs>
  <g filter="url(#sunGlow)">
    <circle cx="12" cy="12" r="6" fill="url(#sunRadial)"/>
    <path d="M12 1L12 3M12 21L12 23M4.22 4.22L5.64 5.64M18.36 18.36L19.78 19.78M1 12L3 12M21 12L23 12M4.22 19.78L5.64 18.36M18.36 5.64L19.78 4.22"
          stroke="#FFB000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
  </g>
</svg>
{% endmacro %}

{% macro moon(class_) %}
    <svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" viewBox="0 0 24 24">
  <defs>
    <linearGradient id="moonLinear" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:#B0BEC5;stop-opacity:1" />
      <stop offset="100%" style="stop-color:#78909C;stop-opacity:1" />
    </linearGradient>
    <filter id="moonShadow" x="-50%" y="-50%" width="200%" height="200%">
      <feDropShadow dx="0" dy="0" stdDeviation="0.5" flood-color="rgba(0, 0, 0, 0.2)" flood-opacity="1"/>
    </filter>
  </defs>
  <g filter="url(#moonShadow)">
    <path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z" fill="url(#moonLinear)" stroke="#546E7A" stroke-width="0.5"/>
    
    <path fill="#FFEB3B" d="M17.5 5.5l0.5 1l1 0.5l-1 0.5l-0.5 1l-0.5-1l-1-0.5l1-0.5z"/>
    <path fill="#FFEB3B" d="M19 12l0.5 1l1 0.5l-1 0.5l-0.5 1l-0.5-1l-1-0.5l1-0.5z" transform="scale(0.8) translate(5, 5)"/>
  </g>
</svg>
{% endmacro %}