movie_library/routes.py
import uuid
import datetime
import functools
from flask import (
    Blueprint,
    render_template,
    session,
    redirect,
    request,
    current_app,
    url_for,
    flash,
)
from dataclasses import asdict
from movie_library.forms import MovieForm, ExtendedMovieForm, RegisterForm, LoginForm, ResetPasswordForm, RequestResetForm, UpdateAccountForm
from movie_library.models import Movie, User
from passlib.hash import pbkdf2_sha256
from flask_mail import Message
from movie_library import mail
from pymongo.errors import DuplicateKeyError


pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)

def login_required(route):
    """
    A decorator to ensure a user is logged in before accessing a route.

    If the user is not logged in, they are redirected to the login page.

    Args:
        route (function): The route to protect.

    Returns:
        function: The decorated route.
    """

    @functools.wraps(route)
    def route_wrapper(*args, **kwargs):
        if session.get("email") is None:
            return redirect(url_for(".login"))

        return route(*args, **kwargs)

    return route_wrapper


@pages.route("/")
@login_required
def index():
    """
    Renders the user's movie watchlist.

    Returns:
        str: The rendered HTML of the index page.
    """
    user_data = current_app.db.user.find_one({"email": session["email"]})
    user = User(**user_data)

    movie_data = current_app.db.movie.find({"_id": {"$in": user.movies}})
    movies = [Movie(**data) for data in movie_data]
    return render_template(
        "index.html",
        title="Movies Watchlist",
        movies_data=movies,
    )


@pages.route("/register", methods=["GET", "POST"])
def register():
    """
    Renders the registration page and handles user registration.

    If the user is already logged in, they are redirected to the index page.

    Returns:
        str: The rendered HTML of the registration page.
    """
    if session.get("email"):
        return redirect(url_for(".index"))

    form = RegisterForm()

    if form.validate_on_submit():
        user = User(
            _id=uuid.uuid4().hex,
            email=form.email.data,
            password=pbkdf2_sha256.hash(form.password.data),
        )

        if current_app.db.user.find_one({"email": form.email.data}):
            flash("An account with this email already exists.", category="danger")
            return redirect(url_for(".register"))

        try:
            current_app.db.user.insert_one(asdict(user))
        except DuplicateKeyError:
            flash("An account with this email already exists.", category="danger")
            return redirect(url_for(".register"))

        flash("User registered successfully!", "success")

        return redirect(url_for(".login"))

    return render_template(
        "register.html", title="Movies Watchlist - Register", form=form
    )

@pages.route("/login", methods=["GET", "POST"])
def login():
    """
    Renders the login page and handles user login.

    If the user is already logged in, they are redirected to the index page.

    Returns:
        str: The rendered HTML of the login page.
    """
    if session.get("email"):
        return redirect(url_for(".index"))

    form = LoginForm()

    if form.validate_on_submit():
        user_data = current_app.db.user.find_one({"email": form.email.data})
        if not user_data:
            flash("Login failed. Please check your email and password.", category="danger")
            return redirect(url_for(".login"))
        
        user = User(**user_data)

        if user and pbkdf2_sha256.verify(form.password.data, user.password):
            session["user_id"] = user._id
            session["email"] = user.email

            return redirect(url_for(".index"))
        
        flash("Login failed. Please check your email and password.", category="danger")

    return render_template("login.html", title="Movies Watchlist - Login", form=form)
            

@pages.route("/account", methods=["GET", "POST"])
@login_required
def account():
    """
    Renders the account page and handles updating user account information.
    """
    form = UpdateAccountForm()

    if form.validate_on_submit():
        user_data = current_app.db.user.find_one({"email": session["email"]})
        user = User(**user_data)

        # Verify current password
        if user and pbkdf2_sha256.verify(form.password.data, user.password):
            # Update email
            current_app.db.user.update_one(
                {"_id": user._id},
                {"$set": {"email": form.email.data}}
            )
            # Update session email
            session["email"] = form.email.data

            flash("Your account has been updated!", "success")
            return redirect(url_for(".account"))
        else:
            flash("Incorrect password. Please try again.", "danger")
    elif request.method == "GET":
        # Pre-fill the form with current user data
        form.email.data = session["email"]

    return render_template("account.html", title="Account", form=form)

@pages.route("/logout")
def logout():
    """
    Logs the user out and redirects to the login page.

    Returns:
        werkzeug.utils.redirect: A redirect to the login page.
    """
    current_theme = session.get("theme")
    session.clear()
    session["theme"] = current_theme

    return redirect(url_for(".login"))


def send_reset_email(user):
    """
    Sends a password reset email to the user.

    Args:
        user (User): The user to send the email to.
    """
    token = user.get_reset_token()
    msg = Message(
        "Password Reset Request",
        recipients=[user.email],
    )
    msg.body = f"""To reset your password, visit the following link:
{url_for('pages.reset_token', token=token, _external=True)}

If you did not make this request then simply ignore this email and no changes will be made.
"""
    mail.send(msg)


@pages.route("/reset_request", methods=["GET", "POST"])
def reset_request():
    """
    Renders the page to request a password reset and handles the form submission.
    """
    if session.get("email"):
        return redirect(url_for(".index"))
    form = RequestResetForm()
    if form.validate_on_submit():
        user_data = current_app.db.user.find_one({"email": form.email.data})
        if user_data:
            user = User(**user_data)
            send_reset_email(user)
        flash("An email has been sent with instructions to reset your password.", "info")
        return redirect(url_for(".login"))
    
    return render_template("reset_request.html", title="Reset Password", form=form)

@pages.route("/reset_request/<token>", methods=["GET", "POST"])
def reset_token(token):
    """
    Renders the page to reset a user's password and handles the form submission.
    """
    if session.get("email"):
        return redirect(url_for(".index"))
    user = User.verify_reset_token(token)
    if user is None:
        flash("That is an invalid or expired token", "warning")
        return redirect(url_for(".reset_request"))
    
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = pbkdf2_sha256.hash(form.password.data)
        current_app.db.user.update_one(
            {"_id": user._id}, 
            {"$set": {"password": hashed_password}}
        )
        flash("Your password has been updated! You can now log in.", "success")
        return redirect(url_for(".login"))
    return render_template("reset_token.html", title="Reset Password", form=form)



@pages.route("/add", methods=["GET", "POST"])
@login_required
def add_movie():
    """
    Renders the add movie page and handles adding a new movie.

    Returns:
        str: The rendered HTML of the add movie page.
    """
    form = MovieForm()

    if form.validate_on_submit():
        movie = Movie(
            _id=uuid.uuid4().hex,
            title=form.title.data,
            director=form.director.data,
            year=form.year.data,
        )

        current_app.db.movie.insert_one(asdict(movie))
        current_app.db.user.update_one(
            {"_id": session["user_id"]}, {"$push": {"movies": movie._id}}
        )


        return redirect(url_for(".movie_added", _id=movie._id))

    return render_template(
        "new_movie.html",
        title="Movies Watchlist - Add Movie",
        form=form,
    )


@pages.route("/added/<string:_id>")
def movie_added(_id: str):
    """
    Renders a confirmation page after a movie has been added.

    Args:
        _id (str): The ID of the movie that was added.

    Returns:
        str: The rendered HTML of the movie added page.
    """
    movie = Movie(**current_app.db.movie.find_one({"_id": _id}))
    return render_template("movie_added.html", movie=movie)


@pages.route("/edit/<string:_id>", methods=["GET", "POST"])
@login_required
def edit_movie(_id: str):
    """
    Renders the edit movie page and handles editing a movie.

    Args:
        _id (str): The ID of the movie to edit.

    Returns:
        str: The rendered HTML of the edit movie page.
    """
    movie = Movie(**current_app.db.movie.find_one({"_id": _id}))
    form = ExtendedMovieForm(obj=movie)
    if form.validate_on_submit():
        movie.title = form.title.data
        movie.director = form.director.data
        movie.year = form.year.data
        movie.cast = form.cast.data
        movie.series = form.series.data
        movie.tags = form.tags.data
        movie.description = form.description.data
        movie.video_link = form.video_link.data
        movie.image_link = form.image_link.data

        current_app.db.movie.update_one({"_id": movie._id}, {"$set": asdict(movie)})

        return redirect(url_for(".movie", _id=movie._id))
    return render_template("movie_form.html", movie=movie, form=form)


@pages.get("/movie/<string:_id>")
def movie(_id: str):
    """
    Renders the movie details page.

    Args:

movie_library/templates/account.html
{% from "macros/fields.html" import render_text_field %} {% extends
"layout.html" %} {% block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/forms.css') }}"
/>
{% endblock %} {% block main_content %}
<form method="POST" action="" novalidate class="form">
  {% with messages = get_flashed_messages(with_categories=true) %} {%- for
  category, message in messages %}
  <span class="form__flash form__flash--{{category}}">{{ message }}</span>
  {% endfor %} {% endwith %}

  <div class="form__container">
    {{ form.hidden_tag() }} {{ render_text_field(form.email) }} {{
    render_text_field(form.password) }}

    <div>{{ form.submit_button(class="button button--form") }}</div>
  </div>
</form>

{% endblock %}

movie_library/templates/index.html
{% extends "layout.html" %} {% block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/movies.css') }}"
/>
{% endblock %} {% block main_content %} {% if movies_data %}
<table class="table">
  <colgroup>
    <col style="width: 60%" />
    <col style="width: 25%" />
    <col style="width: 15%" />
  </colgroup>

  <thead>
    <th class="table__cell table__cell--header">Title</th>
    <th class="table__cell table__cell--header">Release Date</th>
    <th class="table__cell table__cell--header"></th>
  </thead>
  <tbody>
    {% for movie in movies_data %}
    <tr>
      <td class="table__cell">
        <p class="table__movieTitle">{{ movie.title }}</p>
        <p class="table__movieDirector">{{ movie.director }}</p>
      </td>
      <td class="table__cell">{{ movie.year }}</td>
      <td class="table__cell">
        <a
          href="{{ url_for('pages.movie', _id=movie._id) }}"
          class="table__link"
          >View</a
        >
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p class="table__empty">
  No movies in your watchlist.
  <a href="{{ url_for('pages.add_movie') }}" class="link">Add a new movie</a>
</p>
{% endif %}

<a href="{{ url_for('pages.add_movie') }}" class="button button--add">
  <span>+</span>
</a>
{% endblock %}

movie_library/templates/layout.html
{% from "macros/nav.html" import header %} {% from "macros/footer.html" import
footer %}

<!DOCTYPE html>
<html lang="en" class="{{ 'dark-mode' if session.get('theme') == 'dark' }}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>{{ title | default('Movie Watchlist') }}</title>
    <link
      href="https://fonts.googleapis.com/css?family=Public+Sans:400,600&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/reset.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/main.css') }}"
    />

    {% block head_content %} {% endblock %}
  </head>

  <body>
    {{ header(session.get("email"), session.get("theme")) }}
    <main class="main">{% block main_content %} {% endblock %}</main>
    {{ footer(current_year) }}
  </body>
</html>

movie_library/templates/login.html
{% from "macros/fields.html" import render_text_field %} {% extends
"layout.html" %} {% block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/forms.css') }}"
/>
{% endblock %} {% block main_content %}

<form name="login" method="post" novalidate class="form">
  {% with messages = get_flashed_messages(with_categories=true) %} {%- for
  category, message in messages %}
  <span class="form__flash form__flash--{{category}}">{{ message }}</span>
  {% endfor %} {% endwith %}

  <div class="form__container">
    {{ form.hidden_tag() }} {{ render_text_field(form.email) }} {{
    render_text_field(form.password) }}

    <span class="form__small">
      Don't have an account?
      <a href="{{ url_for('.register') }}" class="form__link">Register here</a>.
    </span>
    <span class="form__small">
      <a class="form__link" href="{{ url_for('.reset_request') }}"
        >Forgot password?</a
      >
    </span>

    <div>{{ form.submit(class="button button--form") }}</div>
  </div>
</form>

{% endblock %}

movie_library/templates/movie_added.html
{% extends "layout.html" %} {% block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/movie_added.css') }}"
/>
{% endblock %} {% block main_content %}
<div class="container movie-added">
  <h1 class="movie-added__title">{{ movie.title }} Added Successfully!</h1>
  <p class="movie-added__message">
    The movie "{{ movie.title }}" ({{ movie.year }}) by {{ movie.director }} has
    been added to your watchlist.
  </p>
  <a class="button__link" href="{{ url_for('pages.movie', _id=movie._id) }}"
    >&#127909; View Movie Details</a
  >
  <a
    class="button__link"
    href="{{ url_for('pages.edit_movie', _id=movie._id) }}"
    >&#10133; Add more details</a
  >

  <a class="button__link" href="{{ url_for('pages.index') }}"
    >&#128281; Back to Watchlist</a
  >
</div>
{% endblock %}

movie_library/templates/movie_details.html
{% extends "layout.html" %} {% block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/movie_details.css') }}"
/>
{% endblock %} {% block main_content %}
<div class="container">
  <header class="movie-header">
    <div class="header__row">
      <div class="movie__name">
        <h1 class="movie__title">
          <span class="movie__title-text">{{ movie.title }}</span>
          <span class="movie__title-year">({{ movie.year }})</span>
        </h1>
      </div>
      <div class="movie__watched">
        {% if movie.last_watched %}
        <p>
          Last watched:
          <a
            href="{{ url_for('pages.watch_today', _id=movie._id) }}"
            class="watched__link"
          >
            <time datetime="{{ movie.last_watched }}"
              >{{ movie.last_watched.strftime('%d %b %y') }}</time
            >
          </a>
        </p>
        {% else %}
        <p>
          <a
            href="{{ url_for('pages.watch_today', _id=movie._id) }}"
            class="watched__link"
            >Not watched yet</a
          >
        </p>
        {% endif %}
        <!-- an edit link with an icon of a pencil set as a symbol inside my icons.svg file  -->
        <a
          class="movie__edit"
          href="{{ url_for('pages.edit_movie', _id=movie._id) }}"
        >
          Edit
          <span>
            <svg>
              <use
                href="{{ url_for('static', filename='img/icons.svg') }}#icon-pencil"
              ></use>
            </svg>
          </span>
        </a>
      </div>
    </div>
    <div class="header__row">
      <ul class="movie__tags">
        {% for tag in movie.tags %}
        <li class="movie__tag">{{ tag }}</li>
        {% endfor %}
      </ul>
    </div>
  </header>

  <div class="movie__details--grid">
    {% if movie.image_link %}
    <img
      class="movie__image"
      src="{{ movie.image_link }}"
      alt="{{ movie.title }} poster"
    />
    {% else %}
    <img
      class="movie__image"
      src="{{ url_for('static', filename='img/placeholder.png') }}"
      alt="{{ movie.title }} poster placeholder"
    />
    {% endif %}

    <div class="movie__castCrew">
      {% if movie.director %}
      <div class="movie__director">
        <h2>Director</h2>
        <ul class="list">
          {% if movie.director is iterable and movie.director is not string %}
          {% for director in movie.director %}
          <li class="list__item">{{ director }}</li>
          {% endfor %} {% else %}
          <li class="list__item">{{ movie.director }}</li>
          {% endif %}
        </ul>
      </div>
      {% endif %} {% if movie.cast %}
      <div class="movie__casting">
        <h2>Cast</h2>
        <ul class="list">
          {% for actor in movie.cast %}
          <li class="list__item">{{ actor }}</li>
          {% endfor %}
        </ul>
      </div>
      {% endif %}
    </div>

    <div class="movie__description--details">
      {% if movie.description %}
      <h2>Synopsis</h2>
      <p class="movie__description">{{ movie.description }}</p>
      {% else %}
      <p class="movie__no--description">
        No description yet. <a href="#" class="link">Add one?</a>
      </p>
      {% endif %}
    </div>
  </div>

  <div class="movie__rating">
    {% for i in range(5) %}
    <a
      class="rating__link"
      href="{{ url_for('pages.rate_movie', _id=movie._id, rating=i+1) }}"
    >
      <svg class="star {{ 'filled' if movie.rating > i else '' }}">
        <use
          href="{{ url_for('static', filename='img/icons.svg') }}#icon-star"
        ></use>
      </svg>
    </a>
    {% endfor %}
  </div>

  {% if movie.video_link %}
  <iframe
    class="movie__video"
    src="{{ movie.video_link }}"
    title="YouTube video player"
    frameborder="0"
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
    allowfullscreen
  ></iframe>
  {% endif %}

  <div class="movie__meta">
    {% if movie.series | length %}
    <div class="movie__series">
      <h2>Series</h2>
      <ul class="list">
        {% for movie_in_series in movie.series %}
        <li class="list__item">{{ movie_in_series }}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}
  </div>
  {% endblock %}
</div>

movie_library/templates/movie_form.html
{% from "macros/fields.html" import render_text_field, render_area_field %} {%
extends "layout.html" %} {% block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/forms.css') }}"
/>
{% endblock %} {% block main_content %}
<form name="add_movie" method="post" novalidate class="form">
  <div class="form__container">
    {{ form.hidden_tag() }} {{ render_text_field(form.title) }} {{
    render_text_field(form.director) }} {{ render_text_field(form.year) }} {{
    render_area_field(form.cast) }} {{ render_area_field(form.series) }} {{
    render_area_field(form.tags) }} {{ render_area_field(form.description) }} {{
    render_text_field(form.video_link) }} {{ render_text_field(form.image_link)
    }}

    <div>{{ form.submit(class="button button--form") }}</div>
  </div>
</form>
{% endblock %}

movie_library/templates/new_movie.html
{% from "macros/fields.html" import render_text_field %} {% extends
"layout.html" %} {% block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/forms.css') }}"
/>
{% endblock %} {% block main_content %}
<form name="add_movie" method="post" novalidate class="form">
  <div class="form__container">
    {{ form.hidden_tag() }} {{ render_text_field(form.title) }} {{
    render_text_field(form.director) }} {{ render_text_field(form.year) }} {{
    form.submit(class="button button--form") }}
  </div>
</form>
{% endblock %}

movie_library/templates/register.html
{% from "macros/fields.html" import render_text_field %}

{% extends "layout.html" %}

{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}

    <form name="register" method="post" novalidate class="form">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {%- for category, message in messages %}
                <span class="form__flash form__flash--{{category}}">{{ message }}</span>
            {% endfor %}
        {% endwith %}

        <div class="form__container">
            {{ form.hidden_tag() }}
            
            {{ render_text_field(form.email) }}
            {{ render_text_field(form.password) }}
            {{ render_text_field(form.confirm_password) }}

            <span class="form__small">
                Already have an account? <a href="{{ url_for('.login') }}" class="form__link">Log in here</a>.
            </span>

            <div>
                {{ form.submit(class="button button--form") }}
            </div>
        </div>
    </form>

{% endblock %}

movie_library/templates/reset_request.html
{% from "macros/fields.html" import render_text_field %} {% extends
"layout.html" %} {% block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/forms.css') }}"
/>
{% endblock %} {% block main_content %}
<form method="POST" action="" novalidate class="form">
  {% with messages = get_flashed_messages(with_categories=true) %} {%- for
  category, message in messages %}
  <span class="form__flash form__flash--{{category}}">{{ message }}</span>
  {% endfor %} {% endwith %}

  <div class="form__container">
    {{ form.hidden_tag() }} {{ render_text_field(form.email) }}

    <div>{{ form.submit_button(class="button button--form") }}</div>
  </div>
</form>

{% endblock %}

movie_library/templates/reset_token.html
{% from "macros/fields.html" import render_text_field %} {% extends
"layout.html" %} {% block head_content %}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/forms.css') }}"
/>
{% endblock %} {% block main_content %}
<form method="POST" action="" novalidate class="form">
  {% with messages = get_flashed_messages(with_categories=true) %} {%- for
  category, message in messages %}
  <span class="form__flash form__flash--{{category}}">{{ message }}</span>
  {% endfor %} {% endwith %}

  <div class="form__container">
    {{ form.hidden_tag() }} {{ render_text_field(form.password) }} {{
    render_text_field(form.confirm_password) }}

    <div>{{ form.submit_button(class="button button--form") }}</div>
  </div>
</form>

{% endblock %}